### ISSUE TITLE
npm install breeze-client@latest is installing the alpha version

### ISSUE THREAD

**Issue by rrajewski** [Breeze/breeze-client#13]
`npm install breeze-client@latest` installs 2.0.0-alpha.11 instead of 1.7.1

**Comment by steveschmitt** [comment]
Sorry, that was a mistake!  Will fix.

**Comment by steveschmitt** [comment]
Fixed.  @latest points to 1.7.2 now.  It's the same as 1.7.1, just an version bump so npm would accept it.

Thanks for pointing it out.
