### ISSUE TITLE
ES2015 angular issue on chrome 69 (bug on es5 build)

### ISSUE THREAD

**Issue by badre429** [Breeze/breeze-client#14]
chrome 69 issue 
![issue-chrome69](https://user-images.githubusercontent.com/5818051/59913442-0d988e00-9410-11e9-8990-a1f9adaefa73.JPG)
on chrome 75 work fine

**Comment by steveschmitt** [comment]
I thought the ES5 build process would fix that.

You can fix it by adding the following line in `polyfills.ts`:

    globalThis = window;

**Comment by badre429** [comment]
its works for me
