### ISSUE TITLE
breeze 2.0 : ExecuteQuery fires exception when using JsonResultsAdapter

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze-client#15]
With breeze 1.7 the following code is working :

<code>
     query = query.using( new JsonResultsAdapter(BreezeAdapter.dtoAdapter) );
     this._entityManagerService.em.executeQuery(query)
</code>

where  `BreezeAdapter.dtoAdapter` is static and defines the adapter with extractResults and visitNode methods.

With breeze 2.0 I get an exception `core.js:7187 ERROR Error: Invalid value for property: name`

There are 5 different overrides for `using ()`, if I use the one that takes a DataService as parameter, it works : 

<code>
      this._entityManagerService.em.dataService.jsonResultsAdapter = new JsonResultsAdapter(adapter);.

        query = query.using(this._entityManagerService.em.dataService);

</code>

However, I'd like to pass a JsonResultsAdapter instead of redefining it on the entityManager dataService. 

Again, this code worked with previous version. Is this somehow related to the registering of AjaxHttpClientAdapter ?

**Comment by steveschmitt** [comment]
The JsonResultsAdapter should have a `name` property.  Is it being set?

**Comment by graphicsxp** [comment]
yes it does 

```
export class BreezeAdapter {
    constructor() { }

    static dtoAdapter  =
        {
            name: 'dtoAdapter',
            extractResults: (data: any) => {
                const results = data.results;

                if (results.contractors) {
                    return results.contractors;
                }

                return results;
            },
            visitNode: (node: any, mappingContext: MappingContext, nodeContext: NodeContext) => {
}
```

**Comment by steveschmitt** [comment]
From the code, it looks like it can't figure out what kind of thing you're `using`.  But since you use the `new JsonResultsAdapter(config)` constructor, it should be obvious from the constructor name and the internal `_$typeName` property on the JsonResultsAdapter.  

Strange problem, and I haven't been able to reproduce it.

**Comment by steveschmitt** [comment]
@graphicsxp Did you ever get past this?

**Comment by graphicsxp** [comment]
@steveschmitt I no longer work on the project for which I had this issue and I honnestly do not remember. I think I found a workaround in the end but I will close this ticket. Thanks.
