### ISSUE TITLE
Correct way to register validator factory

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze-client#16]
I'm using `registerFactory` to register custom validators. The following code used to compile with Angular 7 (in prod and dev), but with Angular 8, it gives an error because of the returned type. It expects a `boolean` when I return a `Validator`. 
This makes sense because the ValidationFn interface returns indeed a `boolean` (but then why don't I get this error with Angular 7... ?)

Although compilation gives an error, it works fine at runtime when running with `ng serve`.

In order to fix the problem, I am returning `any` instead of `Validator`, but it seems more like a hack.
This is my code below. Is this the correct way to register a validator factory ? 

<code>

      @Injectable()
      export class CustomValidatorService {

    constructor() {
    }

    initialize() {
        Validator.registerFactory((options) => this.greaterThanValidator(options), 'greaterThanValidator');
    }

     public greaterThanValidator(currentValue): any {    -> RETURNING ANY INSTEAD OF VALIDATOR 
     TO AVOID COMPILATION ERROR
        const name = 'greaterThanValidator';
        const ctx = {
            value: currentValue,
            messageTemplate: '<span class="control-mandatory help-inline invalid"><i class="fa fa-asterisk"></i></span>'
        };

        const validator = new Validator(name, _valFunction, ctx);

        function _valFunction(value, context) {
            if (value === null) {
                return true;
            }
            if (typeof (value) !== 'number') {
                return false;
            }
            if (context.min !== null && value <= context.value) {
                return false;
            }

            return true;
        }

        return validator;
    }

</code>

**Comment by steveschmitt** [comment]
The signature of `Validator.registerFactory` was incorrect, and will be fixed in the next release.

**Comment by steveschmitt** [comment]
Fixed in `breeze-client@2.0.0-beta.1`

**Comment by graphicsxp** [comment]
ok, it's fixed
