### ISSUE TITLE
globalThis is not defined 

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze-client#17]
The globalThis trick gives me an error when running the application in Microsoft Edge. It works fine with Chrome.
        <code>
        // register all validators
        globalThis['x'] = core.objectForEach(Validator, function (key, value) {    -> fails here
     </code>

It gives error :  'globalThis' is not defined
Do you see the same problem on your side ?

**Comment by steveschmitt** [comment]
You would need a polyfill for it in Edge and older browsers.  It can be as simple as:

    var globalThis = window;

In an Angular app, you would put that line in polyfills.ts.

To really polyfill it properly [is much more complicated](https://mathiasbynens.be/notes/globalthis) but not necessary in an app.

**Comment by graphicsxp** [comment]
I've tried your suggestion and added this line to my polyfills.ts file :

`var globalThis = window;`

but that does not solve the problem, I still got the error message. I've tried to use it before or after importing zone.js, but it's the same.

Anything else I should do ?

**Comment by steveschmitt** [comment]
Hmm.  Maybe you have to do

    (window as any).globalThis = window;

**Comment by graphicsxp** [comment]
yes that works ! Not sure I understand the difference though.... :p
