### ISSUE TITLE
Error: Parameter name: modelMetadata

### ISSUE THREAD

**Issue by ganySA** [Breeze/breeze-client#18]
Hi

On .net core 2.2 with breeze 1.x when i try save, it sends data to the server but before even firing the api savechanges method it returns with the following:

Error: Value cannot be null.
Parameter name: modelMetadata

Is there anymore info on this? I cannot seem to find a modelMetadata value in the json being sent to the server?

"`{"$id":"208","$type":"Breeze.AspNetCore.ErrorDto, Breeze.AspNetCore.NetCore","Code":0,"Message":"Value cannot be null.\nParameter name: modelMetadata","StackTrace":"   at Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.EnterNestedScope(ModelMetadata modelMetadata, String fieldName, String modelName, Object model)\n   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinder`2.TryBindStrongModel[TModel](ModelBindingContext bindingContext, IModelBinder binder, String propertyName, String propertyModelName)\n   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinder`2.BindModelAsync(ModelBindingContext bindingContext)\n   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinder`1.BindComplexCollectionFromIndexes(ModelBindingContext bindingContext, IEnumerable`1 indexNames)\n   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinder`1.BindModelAsync(ModelBindingContext bindingContext)\n   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinder`2.BindModelAsync(ModelBindingContext bindingContext)\n   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()","EntityErrors":null}"`

**Comment by ganySA** [comment]
Solved:

Had to include [FromBody]

 [HttpPost]
     ```
   public SaveResult SaveChanges([FromBody] JObject saveBundle)
        { }
```


This used to work in asp.net 4.x
```
 [HttpPost]
        public SaveResult SaveChanges(JObject saveBundle)
        {
}
```

**Comment by yepolonais** [comment]
Thanks a lot @ganySA you saved my afternoon
