### ISSUE TITLE
globalThis is not defined

### ISSUE THREAD

**Issue by KannanRams** [Breeze/breeze-client#21]
Hmm.  Maybe you have to do

    (window as any).globalThis = window;

_Originally posted by @steveschmitt in https://github.com/Breeze/breeze-client/issues/17#issuecomment-507547597_

tried your suggestion. still getting same error.

While trying to run 
node generate-entities.js

**Comment by KannanRams** [comment]
adding globalThis = this;
solved the issue;

globalThis = this;
const tsGen = require('breeze-entity-generator/tsgen-core');
const fs = require('fs');
const dir = './src/app/model';

**Comment by steveschmitt** [comment]
FYI I just published `2.0.0-alpha.16`, which removes the dependency on `globalThis`

Breeze doesn't _use_ a global object, but without it, some JavaScript optimizers (e.g. Terser) want to remove some internal breeze code because it has no side effects.
