### ISSUE TITLE
Infinite calls to toJSONSafe with breeze 2 (not happening in breeze 1.7)

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze-client#22]
I noticed that in one particular case, I run into an "almost" infinite loop calling toJSONSafe from _prepareSaveBundle.

I have an entity of type EntityA with an unmapped property, which is an array of entities EntityB.

Both EntityA and EntityB are registered complex types. 

When saving EntityA, the toJSONSafe method goes through every properperties of EntityB, including things like EntityAspect, EntityGroup, etc.... Hence it takes forever to loop through all these properties. 

I guess this is not the expected behaviour. Is there a way to prevent that from happening ? With breeze 1.7, I don't have the problem (and my code is the same)

**Comment by graphicsxp** [comment]
Ok, I've solved it but I think it is a breaking change.

My unmapped property was defined as : 

myProperty : EntityB [] = [];

If I defined it like this : 

myProperty : Array<EntityB>;

It works fine ! Any idea why ?

**Comment by steveschmitt** [comment]
Interesting!  Do you have some code I can use to reproduce the problem?

**Comment by graphicsxp** [comment]
I don't really have code that is easy to share but here's my entity's class that I'm trying to save. I basically add/remove elements to the `selectedLanguages` array and then I loop trough the array to update my `referenceLanguages` array. It's a many-2-many association and that's why I have to use a temporary unmapped array, which is bound to the UI.

Like I said before, if I define the unmapped array like this instead :  
`selectedLanguages:  Language[ ] = [ ]`  then it will break on saveChanges and breeze will try to parse every objects in the graph when calling toJSONSafe.

```
export class Reference extends EntityBase {

    static breezeName = 'Reference';

    selectedLanguages: Array<Language>;
    isScreenDeleted: Boolean = false;

    postInitialiazer(metadataStore: MetadataStore) {
        metadataStore.registerEntityTypeCtor('Reference', Reference, this.referenceInitializer);
    }

    id: string;
    version: number;
    createdBy: string;
    updatedBy: string;
    creationDate: Date;
    updateDate: Date;
    isDeleted: boolean;
    materialId: string;
    referenceSetId: string;
    referenceLanguages: ReferenceLanguage[];
}
```
My configuration, if it helps :  

Angular CLI: 8.2.0
Node: 10.16.0
OS: win32 x64
Angular: 8.2.0
TypeScript: 3.4.5
Breeze-client :  2.0.0-alpha.17

**Comment by steveschmitt** [comment]
I still haven't been able to reproduce the problem.  I noticed that when you use 
``` selectedLanguages: Array<Language>; ```
that you don't initialize it to a value (e.g. using ` = []` but you did that when using
``` selectedLanguages: Language[] = []; ```
Could that make a difference?  

Does anything happen to `selectedLanguages` in your `referenceInitializer`?  
Does the `Language` entity have navigations to other entities?

**Comment by graphicsxp** [comment]
yes, in the referenceIntializer I actually initialize the array : 

```
 public referenceInitializer = (reference: Reference) => {
        this.selectedLanguages = [];
        this.referenceLanguages.forEach((tl) => {
            this.selectedLanguages.push(tl.language);
        });
}
```

**Comment by steveschmitt** [comment]
Thanks for the additional info.  What does the metadata look like for Reference and Language?

**Comment by graphicsxp** [comment]
Language :

` {
      "shortName": "Language",
      "namespace": "EAI.Model.Business",
      "autoGeneratedKeyType": "KeyGenerator",
      "defaultResourceName": "Languages",
      "dataProperties": [
        {
          "nameOnServer": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "nameOnServer": "Version",
          "dataType": "Int32",
          "isNullable": false,
          "concurrencyMode": "Fixed",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "int32"
            }
          ]
        },
        {
          "nameOnServer": "CreatedBy",
          "dataType": "String",
          "isNullable": true
        },
        {
          "nameOnServer": "UpdatedBy",
          "dataType": "String",
          "isNullable": true
        },
        {
          "nameOnServer": "CreationDate",
          "dataType": "DateTime",
          "isNullable": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "date"
            }
          ]
        },
        {
          "nameOnServer": "UpdateDate",
          "dataType": "DateTime",
          "isNullable": true,
          "validators": [
            {
              "name": "date"
            }
          ]
        },
        {
          "nameOnServer": "IsDeleted",
          "dataType": "Boolean",
          "isNullable": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "bool"
            }
          ]
        },
        {
          "nameOnServer": "Code",
          "dataType": "String",
          "isNullable": false,
          "maxLength": 25,
          "validators": [
            {
              "name": "required"
            },
            {
              "maxLength": 25,
              "name": "maxLength"
            }
          ]
        },
        {
          "nameOnServer": "DefaultLabel",
          "dataType": "String",
          "isNullable": false,
          "validators": [
            {
              "name": "required"
            }
          ]
        },
        {
          "nameOnServer": "ValidFrom",
          "dataType": "DateTime",
          "isNullable": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "date"
            }
          ]
        },
        {
          "nameOnServer": "ValidTo",
          "dataType": "DateTime",
          "isNullable": true,
          "validators": [
            {
              "name": "date"
            }
          ]
        },
        {
          "nameOnServer": "Description",
          "dataType": "String",
          "isNullable": true
        },
        {
          "nameOnServer": "DisplayOrder",
          "dataType": "Int32",
          "isNullable": true,
          "validators": [
            {
              "name": "int32"
            }
          ]
        },
        {
          "nameOnServer": "IsUsed",
          "dataType": "Boolean",
          "isNullable": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "bool"
            }
          ]
        },
        {
          "nameOnServer": "Abbreviation",
          "dataType": "String",
          "isNullable": false,
          "maxLength": 50,
          "validators": [
            {
              "name": "required"
            },
            {
              "maxLength": 50,
              "name": "maxLength"
            }
          ]
        },
        {
          "nameOnServer": "EUEntranceDate",
          "dataType": "DateTime",
          "isNullable": true,
          "validators": [
            {
              "name": "date"
            }
          ]
        },
        {
          "nameOnServer": "EUExitDate",
          "dataType": "DateTime",
          "isNullable": true,
          "validators": [
            {
              "name": "date"
            }
          ]
        },
        {
          "nameOnServer": "IsEULanguage",
          "dataType": "Boolean",
          "isNullable": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "bool"
            }
          ]
        },
        {
          "nameOnServer": "SDLLanguageCode",
          "dataType": "String",
          "isNullable": true
        },
        {
          "nameOnServer": "CultureInfoCode",
          "dataType": "String",
          "isNullable": true
        }
      ],
      "navigationProperties": []
    },`


Then Reference:

` {
      "shortName": "Reference",
      "namespace": "EAI.Model.Business",
      "autoGeneratedKeyType": "KeyGenerator",
      "defaultResourceName": "References",
      "dataProperties": [
        {
          "nameOnServer": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "nameOnServer": "Version",
          "dataType": "Int32",
          "isNullable": false,
          "concurrencyMode": "Fixed",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "int32"
            }
          ]
        },
        {
          "nameOnServer": "CreatedBy",
          "dataType": "String",
          "isNullable": true
        },
        {
          "nameOnServer": "UpdatedBy",
          "dataType": "String",
          "isNullable": true
        },
        {
          "nameOnServer": "CreationDate",
          "dataType": "DateTime",
          "isNullable": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "date"
            }
          ]
        },
        {
          "nameOnServer": "UpdateDate",
          "dataType": "DateTime",
          "isNullable": true,
          "validators": [
            {
              "name": "date"
            }
          ]
        },
        {
          "nameOnServer": "IsDeleted",
          "dataType": "Boolean",
          "isNullable": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "bool"
            }
          ]
        },
        {
          "nameOnServer": "MaterialId",
          "dataType": "Guid",
          "isNullable": true,
          "validators": [
            {
              "name": "guid"
            }
          ]
        },
        {
          "nameOnServer": "ReferenceSetId",
          "dataType": "Guid",
          "isNullable": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "nameOnServer": "Material",
          "entityTypeName": "Material:#EAI.Model.Business",
          "isScalar": true,
          "associationName": "AN_Material_Reference_MaterialId",
          "foreignKeyNamesOnServer": [
            "MaterialId"
          ]
        },
        {
          "nameOnServer": "ReferenceLanguages",
          "entityTypeName": "ReferenceLanguage:#EAI.Model.Business",
          "isScalar": false,
          "associationName": "AN_Reference_ReferenceLanguage_ReferenceId",
          "invForeignKeyNamesOnServer": [
            "ReferenceId"
          ]
        },
        {
          "nameOnServer": "ReferenceSet",
          "entityTypeName": "ReferenceSet:#EAI.Model.Business",
          "isScalar": true,
          "associationName": "AN_Reference_ReferenceSet_ReferenceSetId",
          "foreignKeyNamesOnServer": [
            "ReferenceSetId"
          ]
        }
      ]
    },`

**Comment by steveschmitt** [comment]
I _think_ I fixed it.  Please try `breeze-client@2.0.0-beta.2` and let me know.
