### ISSUE TITLE
No exported member FetchStrategySymbol

### ISSUE THREAD

**Issue by softronsts** [Breeze/breeze-client#23]
Using  "breeze-client": "^2.0.2",

Getting below issue:
node_modules/breeze-client/breeze-client"' has no exported member 'FetchStrategySymbol'

Will you be updating the type definitions for the version 2.0.2?

**Comment by marcelgood** [comment]
Please read the breaking changes section in the README. FetchStrategySymbol is now FetchStrategy. 

https://github.com/Breeze/breeze-client/blob/master/README.md
