### ISSUE TITLE
Allow undefined values in defaultPropertyInterceptor change breaks existing code

### ISSUE THREAD

**Issue by rrajewski** [Breeze/breeze-client#24]
This seems to be the result of how typescript handles optional parameters and the latest change made in version 2.0.2.

Example:

```
optionallySetValueOnEntity(entity: MyEntity, someOtherEntity?: SomeOtherEntity){
   entity.myNavProperty = someOtherEntity; // value is undefined and results in "Cannot read property 'entityAspect' of null error" instead of setting the property to null like it used to
}

this.optionallySetValueOnEntity(myEntity);
```

**Comment by steveschmitt** [comment]
Sounds plausible, but I couldn't duplicate the issue in my tests.  
Please tell me more about your environment.

**Comment by rrajewski** [comment]
- These are angular projects using angular cli to build: "@angular/cli": "8.3.23"
- we also use the enableSaveQueuing mixin import { enableSaveQueuing } from 'breeze-client/mixin-save-queuing';


Narrowed down when it occurs, has to do with the entity creation:

```
var newEntity = mgr.create("MyEntity'); // without an initial value for myNavProp, works ok if an initial value for myNavProp is passed mgr.create("MyEntity', {myNavProp: someEntity});

// before setting, newEntity.myNavProp  === null
newEntity.myNavProp = undefined; // error occurs

```

**Comment by steveschmitt** [comment]
Thanks, I was able to duplicate the problem.  I'll look into a fix.

**Comment by steveschmitt** [comment]
I originally made that change to fix some problem that I observed... but now I can't seem to reproduce that problem!  So I've reverted the change for now, in 2.0.3
