### ISSUE TITLE
Documentation inaccuracy (Metadata by hand (in depth))

### ISSUE THREAD

**Issue by michal-kindl** [Breeze/breeze-client#28]
There is a mistake in description of DataProperties. The 'isNullable' property is described with default value as 'false'. In source code there is in DataProperty constructor initialized to default 'true'.
See  
line 2016:     .whereParam("isNullable").isBoolean().isOptional().withDefault(true)
https://github.com/Breeze/breeze-client/blob/48ba04b/src/entity-metadata.ts#L2016

Also the Doc examples suggests, that isNullable property is default set to true.

**Comment by steveschmitt** [comment]
Fixed now.
