### ISSUE TITLE
Changing a dropdown value results in: Cannot read property entityState of undefined 

### ISSUE THREAD

**Issue by softronsts** [Breeze/breeze-client#29]
Hi,

We are having an issue in binding ngModel with an autocomplete list.

![image](https://user-images.githubusercontent.com/58279809/78985076-73e6cc80-7b5a-11ea-93b4-bddab9ee5339.png)

breeze-client throws above error when we start keying in the characters i.e before one of the list item is selected it jumps to this check.

adding these lines solves the issue.

if(!newValue.entityAspect){
            return;
        }

![image](https://user-images.githubusercontent.com/58279809/78984809-c2e03200-7b59-11ea-96a0-93f11096d837.png)

Is it possible to provide us this amendment?

Thanks & regards,
Fayeeg

**Comment by softronsts** [comment]
Hello,

Could you please respond?

**Comment by marcelgood** [comment]
Sounds like your entity is not attached when you are making your selection. Either way, if you have a suggestion for a code fix, please submit a PR and we'll consider merging it.

**Comment by softronsts** [comment]
I have submitted a PR

**Comment by steveschmitt** [comment]
Fixed via PR #30
