### ISSUE TITLE
Error when assigning compound foreign key with GUID and integer values

### ISSUE THREAD

**Issue by malichishti** [Breeze/breeze-client#3]
Hi,

The issue and potential solution is mentioned at [stackoverflow](https://stackoverflow.com/questions/23682894/breeze-js-error-when-assigning-compound-foreign-key-with-guid-and-integer-value)

Can this be included in next version?

Regards,
Ali

**Comment by steveschmitt** [comment]
Fixed in breeze-client@2.0.0-beta.1
Thanks for your help in fixing this.
