### ISSUE TITLE
Breeze Client Not Filtering

### ISSUE THREAD

**Issue by jj30** [Breeze/breeze-client#31]
Hello, I got the example working, but upon revisiting it, I notice that it's working without filtering. In other words, if I apply a filter to it:
```
     componentDidMount() {
        entityManagerProvider.subscribeComponent(this.manager, this);  
                     
        let predTest = new Predicate('ID', '==', 1);

        const query = new EntityQuery("Programs")
            .where(predTest); 

        this.manager.executeQuery(query).then(qr => {
            this.setState({
                programs: qr.results
            });
        });
```

It returns everything in the 'Programs' table. 

I expected only the first program with ID = 1 to be returned. There is more code, but it's not interesting, as it's assumed that if it were wrong, no results would be returned at all.

Can anyone produce a working example of actual filtering?

**Comment by jj30** [comment]
Seems the URLs formed by the breeze-client differ from the AngularJS breeze client (we are upgrading to React)

http://localhost/lcgapi/breeze/Breeze/OpenTasks?$filter=((ID eq 411) ... 

and

http://localhost/lcgapi/breeze/Breeze/OpenTasks?%7B%22where%22%3A%7B%22AFREID%22%3A411%7D%7D

which translates to

http://localhost/lcgapi/breeze/Breeze/OpenTasks?{"where":{"AFREID":411}}

**Comment by marcelgood** [comment]
The $filter is the old OData query syntax and JSON is the newer and more capable syntax. Most of our newer backends expect the JSON format, but the client can be configured for either one. 

You just need to import the respective `UriBuilder `and register it. 

`import { UriBuilderODataAdapter } from 'breeze-client/adapter-uri-builder-odata';`

or 

`import { UriBuilderJsonAdapter } from 'breeze-client/adapter-uri-builder-json';`

and then 

`UriBuilderODataAdapter.register();`

or 

`UriBuilderJsonAdapter.register();`

You can also register both, and then specify which one to use in `DataServiceConfig.uriBuilderName`.

**Comment by jj30** [comment]
!!!!

It works!!!

Superlative exclamations of breeze client filtering!

It would appear then that our API, which is EF6 (Enterprise Framework) is configured for OData Adapters only.  So your code is great, as we have to run the legacy and the upgrade simultaneously, and so we can't change the API.

Thank you, @marcelgood.

**Comment by marcelgood** [comment]
Yes, our old .NET stack uses the OData syntax. The new .NET Core stack is using JSON.
