### ISSUE TITLE
Do breeze-client/bundles have a dependency on angular ?

### ISSUE THREAD

**Issue by markus-albis** [Breeze/breeze-client#35]
I try to integrate breeze-client into an Aurelia project (aurelia-cli, built-in bundler, systemjs module loader). I'm using the breeze-client/bundles libraries. Upon bundling, I get the following error:

ERROR [PackageAnalyzer] Unable to load package metadata (package.json) of @angular/common:
INFO [PackageAnalyzer] Error: cannot resolve npm package folder for "@angular/common"
ERROR [Bundler] Unable to analyze @angular/common
INFO [Bundler] Error: Unable to find package metadata (package.json) of @angular/common
ERROR [Bundler] Failed to add Nodejs module @angular/common/http
INFO [Bundler] Error: Unable to find package metadata (package.json) of @angular/common

When running the prject I see the following error

aurelia-logging-console.js:51 ERROR [app-router] Error: Unexpected token '<'
  Evaluating http://localhost:9000/@angular/common/http

Seems strange that a pure js library should have any dependencies on a framework like angular ??
Any help to integrate breezejs 2.0 into an Aurelia project would be very welcome

**Comment by marcelgood** [comment]
Certain adapters have dependencies to other libraries. Those adapters are optional and you should only include them in your project if you are using the respective library. The one you seem to be running into is the breeze-client-adapter-ajax-httpclient. This one is to integrate Breeze with the Angular HttpClient. You won't use this one in an Aurelia project, so make sure you don't try to bundle it.

**Comment by markus-albis** [comment]
Thank you for youur feedback. Which adapters are required to use the breeze-client in an Aurelia project. Are there instructions on how to integrate breeze-client in to a framework other than Angular, eg Aurelia ?

**Comment by marcelgood** [comment]
There are no instructions specifically for Aurelia. The main adapters that are required for any app is the correct model library, dataservice adapter and uriBuilder. The latter don't depend on what client framework you are using, but what type of backend you are using. 

For the model library the standard backingStore should work.

`breeze-client/adapter-model-library-backing-store`

For most backends, the webApi dataService adapter should work.

`breeze-client/adapter-data-service-webapi`

but, the the uri adapter is specific to what query syntax your server supports. JSON or OData syntax.

`breeze-client/adapter-uri-builder-odata`
or
`breeze-client/adapter-uri-builder-json`

You will most likely also need an Ajax adapter to integrate with the Aurelia specific HTTP client and make sure Breeze returns compatible promises. By default Breeze uses jQuery Ajax. This is what the `breeze-client/adapter-ajax-httpclient` does for Angular. Unfortunately, we don't currently offer one out of the box, so you'll have to write your own, or maybe somebody else wrote one already and it offering it.

**Comment by steveschmitt** [comment]
With Aurelia, you probably want `adapter-ajax-fetch`

Sorry there's no Aurelia demo app yet.  The closest we have would probably be the [Vue demo](https://github.com/Breeze/northwind-core-ng-demo/tree/master/NorthwindCore/NorthwindVue).
