### ISSUE TITLE
Using AjaxPostWrapper in TypeScript version

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze-client#39]
Hello

would you have a sample that shows how to use the AjaxPostWrapper in TypeScript  ? I've used it in the past with the JavaScript version  but cannot figure out how to use it now.

I guess it should be called in the constructor of my app module (angular) in a similar way 

         export class AppModule {
        constructor( http: HttpClient) {
        ModelLibraryBackingStoreAdapter.register();
        UriBuilderJsonAdapter.register();
        AjaxHttpClientAdapter.register(http);
         DataServiceWebApiAdapter.register();
         AjaxPostWrapper.wrapAjax(  /*  WHAT DO I PASS HERE ?    */)
      }

**Comment by graphicsxp** [comment]
in the end I did that and it works :  
  AjaxPostWrapper.wrapAjax(AjaxHttpClientAdapter.register(http));

can you just conrfirmed this is the correct way  ?

**Comment by steveschmitt** [comment]
Looks good to me!
