### ISSUE TITLE
Custom data on EntityError

### ISSUE THREAD

**Issue by iulianb** [Breeze/breeze-client#42]
I have a use case that requires the server application to send a message code and some message parameters for each validation error. This code is picked up by the client applications and is used for retrieving the localized message text (something along the lines of: `An entity with id <p1> already exists`). This might be a simple example that can probably be handled by existing functionality but there are more complex ones, with multiple parameters that are only available on the server and only at validation time. 

I remember this working in the older versions, that is, `breeze-client` didn't parse the `EntityError` object and simply let it through in the form that arrived from the server.

**Comment by steveschmitt** [comment]
Just so you know, for the example that you gave, there is a `keyValues` property that will give you the id of the entity.  But it makes sense that you might want to pass additional data.  We'll look into it.

**Comment by steveschmitt** [comment]
EntityError now has `custom` property as of release 2.0.9.
