### ISSUE TITLE
client duplicates properties on server-side inheritance

### ISSUE THREAD

**Issue by lvasiliou** [Breeze/breeze-client#44]
Hi I am using TPH inheritance in EF core and I can see the metadata have each property on inherited entities once. However, it appears that client-side all properties are duplicated and calling EntityManager.createEntity results into an error Error: Ids can not be autogenerated for entities with multipart keys. Looks like the entity manager assuming that both properties of the superclass and inheriting class are different.
As a workaround, I removed baseTypeName from metadata generated on the server.

**Comment by steveschmitt** [comment]
There was a bug in the metadata generation in Breeze.Persistence.EFCore - it was duplicating properties between classes in a TPH hierarchy.  Please try updating your Breeze server library to version **3.1.4** for .NETCore 3.1, or to version **5.0.4** for .NET5.

Let me know if that fixes the problem.  Thanks!

**Comment by steveschmitt** [comment]
@lvasiliou Can we close this issue?

**Comment by lvasiliou** [comment]
Hi I had a look today and the properties are double or triple counted based on inheritance depth when iterating through the properties client side
