### ISSUE TITLE
or predicates getting mixed up

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze-client#46]
I came across an odd issue with the following predicate : 

![image](https://user-images.githubusercontent.com/4160415/114581231-d435b000-9c7f-11eb-9b5c-23c54cc0c1ce.png)

the resulting where clause should be : 

`where (statusValue = 1 or statusValue = 4 or statusValue = 5) and (claimedByUserId = "the  guid" or claimedByUserId = null)`

Instead the query sent to the server has the following where clause :   

![image](https://user-images.githubusercontent.com/4160415/114581669-32fb2980-9c80-11eb-8153-63b0843dfea5.png)

The problem seems to be in adapter-uri-builder-json.ts at  line 
`let json = entityQuery.toJSONExt( { entityType: entityType, toNameOnServer: true}) as any;`

I'm using breeze-client 2.0.7.

Any idea how this could be fixed? This is a rather critical issue for me.

SOME MORE INFO :  

If I add a third predicate (just a binary predicate) then the query is built correctly  !  

Check this out; I've added a predicate requetNumber

![image](https://user-images.githubusercontent.com/4160415/114585736-3f818100-9c84-11eb-9e4a-dd2de6c9c9f7.png)

and now the output query is : 

![image](https://user-images.githubusercontent.com/4160415/114585870-5fb14000-9c84-11eb-9ed7-75eb591b7229.png)

looks like a bug to me. Can you confirm  ?

**Comment by steveschmitt** [comment]
Very strange!  I'll look into it.

**Comment by graphicsxp** [comment]
Indeed. For the time being I am adding a dummy predicate to all my queries to force an extra AND on the 'id' of my entity (which is never null)

  `    predicate.push(new Predicate('id', FilterQueryOp.NotEquals, null));`

that forces the query to be built correctly, but that's obviously a hack. I hope you can come up with a solution  !

**Comment by steveschmitt** [comment]
Found the problem - the predicate attempts to simplify the "and" operation but it doesn't work when the clauses are "or" operations.  Will be fixed in next release.

**Comment by steveschmitt** [comment]
Fixed in release **2.1.0**
