### ISSUE TITLE
API Bearer authentication support

### ISSUE THREAD

**Issue by lvasiliou** [Breeze/breeze-client#48]
Hi i am trying to secure my API using bearer header/token. Is there a simple way to achieve this or is it a matter of writing an adapter from scratch?

**Comment by softronsts** [comment]
At client,  you need to wire up the authentication/signin in auth service and for every http request you can attach the token via HttpInterceptor. Sample implementation as follows

```
import { Injectable } from "@angular/core";
import { HttpRequest, HttpHandler, HttpEvent, HttpInterceptor } from "@angular/common/http";
import { Observable } from "rxjs";
import { StorageService } from "../@services/storage.service";
import { tap, finalize } from "rxjs/operators";
import { NgxSpinnerService } from "ngx-spinner";


@Injectable()
export class TokenInterceptor implements HttpInterceptor {
  count = 0;
  constructor(private storage: StorageService, private spinner: NgxSpinnerService) {}
  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    this.spinner.show();

    const token = this.storage.get("auth.access_token");
    request = request.clone({
      setHeaders: {
        Authorization: `Bearer ${token}`,
      },
    });


<snipped>
```

**Comment by lvasiliou** [comment]
Thanks for the reply. I am using React instead of Angular though

**Comment by lvasiliou** [comment]
Thanks for the reply but regrettably I am using React.

**Comment by steveschmitt** [comment]
@lvasiliou There's probably a "React way" of doing this, but here's an example of the Breeze way.
```ts
    // example of adding headers to requests via requestInterceptor
    AjaxFetchAdapter.register().requestInterceptor = (req => {
        console.log(req);
        req.config.headers.Authorization = "Bearer oiwjeglkwjelkj";
      }) as any;
```
I've added this example code to **entity-manager-provider.ts** in the [northwind-demo](https://github.com/Breeze/northwind-demo/tree/master/client/northwind-react/src/model) sample application.

You would still need to implement the creation and handling of the actual tokens, perhaps using local storage as @softronsts suggests above.

BTW, when I looked into this I realized that the declared type for `requestInterceptor` is all wrong in Breeze.  I'll fix it for the next release.

**Comment by lvasiliou** [comment]
Angular always felt more mature with advanced and scalable, with features out of the box. Also way better documented. React works but the focus is too much on components rather than apps.

**Comment by steveschmitt** [comment]
@lvasiliou Shall I close this issue?

**Comment by lvasiliou** [comment]
> @lvasiliou Shall I close this issue?

Yes I was able to inject the bearer token

**Comment by lvasiliou** [comment]
I haven't had a chance to look at this yet but I trust you
