### ISSUE TITLE
entityAspect.setProperty on navigation property rejects entity value of type from TPH inheritance on the server

### ISSUE THREAD

**Issue by lvasiliou** [Breeze/breeze-client#49]
Hi I have a set of entities that use TPH on the server. Trying to assign such entity to a navigation property via entity Aspect.setProperty, the value is cleared with no error. Not sure if this is a side effect of my workaround of issue #44

**Comment by steveschmitt** [comment]
There was a bug in the metadata generation in Breeze.Persistence.EFCore - it was duplicating properties between classes in a TPH hierarchy.  Please try updating your Breeze server library to version **3.1.4** for .NETCore 3.1, or to version **5.0.4** for .NET5.

Let me know if that fixes the problem.  Thanks!

**Comment by steveschmitt** [comment]
@lvasiliou Can we close this issue?
