### ISSUE TITLE
The first expression of this AnyAllPredicate must be a nonscalar Navigation PropertyExpression

### ISSUE THREAD

**Issue by ganySA** [Breeze/breeze-client#51]
Hi

I have written a breeze query which queries along a related entity.

```
var p1= Predicate.create("email", FilterQueryOp.Contains, query);
var p2= Predicate.create("client", FilterQueryOp.Any, p1);
```

The query string being sent to the server is as follows
`{"where":{"Client":{"any":{"Email":{"contains":"mike"}}}},"orderBy":["Date desc"],"expand":["Client"],"skip":0,"take":10,"inlineCount":true}: `

The server seems to .net server seems to panic on this and return:
`The first expression of this AnyAllPredicate must be a nonscalar Navigation PropertyExpression`

I have followed the docs and this seems to be a valid query. Is this a bug?

**Comment by steveschmitt** [comment]
What is the parent entity for the resource endpoint?  According to your query, and the error message, it should be an entity that has many `Client` entities associated to it, with a property such as 
```csharp
ICollection<Client> Client { get; set; }
```

**Comment by ganySA** [comment]
Thanks this led me to the answer. Closing.
