### ISSUE TITLE
After moving away from -labs with latest, can't find exposed "QueueSaveFailedErrror" type

### ISSUE THREAD

**Issue by Prinsn** [Breeze/breeze-client#53]
I believe this may have been used, previously, from breeze-client-labs, but we have a check that was using `instance of` in TS to compare to this type, and it is ostensibly of that type

`constructor: ƒ QueuedSaveFailedError(errObject, saveQueuing)` (This also might be indicative of just really bad coding, as this constructor matches the local clone of the class I created to solve the problem initially, but it doesn't pass `instanceof` checks)

I'm not sure if this is because there are node-modules still for breeze-client-labs (they exist in `node-modules`), because I don't know that we're referencing it and the type does not seem to exist outside of `breeze.savequeuing.js` there in.

Learning just now that the amateur move to just redefine the type locally does not an `instanceof` make.

This is fixable (using .constructor.prototype.name comparison), just not certain if there was any expectation with moving away from what I am assuming was breeze 2.0 beta.

**Comment by steveschmitt** [comment]
Fixed in release 2.1.2.

**Comment by Prinsn** [comment]
🙏 This can probably be closed, but I wont have time to verify it, as my "hackaround" is functional for the moment and I'm now triaging Microsoft's left-right-hand problems.
