### ISSUE TITLE
Breeze client 2.1.0 does not work in IE 11

### ISSUE THREAD

**Issue by kostyabushuev** [Breeze/breeze-client#56]
Hello

After added [this](https://github.com/Breeze/breeze-client/pull/36) pull request breeze-client does not work in IE11.

Added regexp `/Collection\((?<type>.*)\)/` is incorrect for IE11, because `?<!` is not supporting. [Link to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#browser_compatibility)

**Comment by steveschmitt** [comment]
Ah, thanks.  Maybe we can find another way that doesn't use that regex.

**Comment by tschettler** [comment]
The regex wasn't using a look behind, it was just the name captured group causing the issue. Sorry about that!
