### ISSUE TITLE
Version Bump Request

### ISSUE THREAD

**Issue by senseiweb** [Breeze/breeze-client#6]
Breeze Team...I know that is only an alpha release, but it is an adequate guide for building a typescript flavored custom dataservice adapter. The current release breaks fails to build with the @types/jasmin and the latest target ts version. 

I was hoping someone could do a version bump to the latest typescript build and perhaps push it to a beta stage. 

Thanks for the consideration and the work...breeze is still an awesome framework for client data management!

**Comment by steveschmitt** [comment]
Just updated.  I've changed the package structure to match Angular's current format, so some things have changed.

Please try 2.0.0-alpha.9 using `npm install breeze-client@next` and see if everything works for you.  If it seems solid, we'll bump it to beta.

**Comment by steveschmitt** [comment]
Current version is `breeze-client@2.0.0-beta.1`

**Comment by steveschmitt** [comment]
Now officially released.  Current version is 2.0.1.  Please see the [Release Notes](http://breeze.github.io/doc-js/release-notes.html)
