### ISSUE TITLE
executeQueryLocally does not return Entity when EntityQuery has select parameter

### ISSUE THREAD

**Issue by mahish** [Breeze/breeze-client#66]
Im using https://github.com/tschettler/breeze-odata4 adapter, however this should not be affected in any way as far as I understand.

Looks like when using `executeQueryLocally` with `select` parameter, I get an array of simple objects: without `entityType` or `entityAspect`.

```js
const entityQuery = new EntityQuery({
  from: 'entityTypeName',
  select: ['propertyName'],
});

// returns Entity[]
const { results } = await manager.executeQuery(entityQuery);

// but

// returns Record<string, any>[]
const results = manager.executeQueryLocally(entityQuery);
```

https://github.com/Breeze/breeze-client/blob/125f4671cb563ed77c86bb60c4bf7bff75af8396/src/entity-manager.ts#L2510

**Comment by mahish** [comment]
This workaround works but I find… as a workaround. I would expect to get `Entity[]` using both strategies for fetching data.

```js
const entityQuery = new EntityQuery({
  from: 'entityTypeName',
  select: ['propertyName', 'entityType'],
});

// returns `{ propertyName: any, entityType: EntityType }`
const results = manager.executeQueryLocally(entityQuery);
```

**Comment by marcelgood** [comment]
That is the expected behavior. Select does a projection into a simple object using the specified properties. If you run a select against the server it's the same thing. You get simple JS objects. The objects are no longer entities at that point.

**Comment by mahish** [comment]
@marcelgood Thank you for clarification. Make sense and as I can see it is also clearly noted in documentation http://breeze.github.io/doc-js/api-docs/classes/entityquery.html#select . However it is not the case for me. The behaviour is inconsistent. See the screenshot:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/3687943/168229742-d7ba7062-f552-42dd-8726-dae1de184446.png">

So, it seems the behaviour of `executeQuery` (not `executeQueryLocally`) is not the consistent in my case. And since `executeQuery` is  implemented by `breeze-odata4`, I should ask there.

**Comment by marcelgood** [comment]
Yes, that would be an issue with the breeze-odata4 adapter. We didn't write this adapter, nor do we support it. Running a projection query against the server (executeQuery) is supposed to return plain objects. As the documentation states, there can be entities nested, such as when you select a navigation property, but the root object is a plain object. This is how it works with the adapters that are supplied with Breeze out of the box.
