### ISSUE TITLE
will the following packages work in angular 7.3.10

### ISSUE THREAD

**Issue by BlackChesire** [Breeze/breeze-client#72]
I want to update these packages:
    "breeze-bridge2-angular": "^1.1.0",
    "breeze-client": "^1.7.1",

will it work on my angular 7?
and heres my nuget packages:
![image](https://user-images.githubusercontent.com/68661307/212839934-4ef61fa4-939e-46a6-98db-8e69a86e0107.png)

**Comment by steveschmitt** [comment]
I think you should use breeze-client 2.x.  Take a look at the [northwind-demo project](https://github.com/Breeze/northwind-demo) for an example of how to set it up.  

In particular, look at the [/server](https://github.com/Breeze/northwind-demo/tree/master/server) subdirectory for examples on how to set up your server for metadata generation.

Then look at the [STEPS-Client-Angular](https://github.com/Breeze/northwind-demo/blob/master/client/STEPS-Client-Angular.md) document for getting Breeze going with Angular.  The [demo](https://github.com/Breeze/northwind-demo/tree/master/client/northwind-angular) was created with Angular 8, but it's pretty much the same for all versions.
