### ISSUE TITLE
Error in product page

### ISSUE THREAD

**Issue by lcastro-art** [Breeze/breeze-client#75]
Hello. There is an error on the product page when you have the 'Enable Breeze Experience' feature disabled. Let me explain it better, when you have the Breeze blank theme and disable the 'Enable Breeze Experience' option, the thumbnails do not load and only one main image is displayed. Without the thumbnails, you cannot see the other product images. These thumbnails work properly if you enable 'Enable Breeze Experience'. I understand that it should not work like this because this setting should only be used to improve performance and not change the functionality of the gallery. Thank you. Regards.

**Comment by steveschmitt** [comment]
Can you please include a link to the page?

**Comment by lcastro-art** [comment]
Hello steve,
The error appears in the base breeze template, so you can reproduce it in your own breeze demo. I'm sharing screenshots to be able to reproduce it. Note: I have updated breeze to the latest version 2.3.

1. Content -> Design -> Configuration -> Edit a Store -> Default Theme -> Applied Theme -> and Select "Breeze Blank"
![b1](https://user-images.githubusercontent.com/61665158/224704086-4cfd7909-28f7-4cb4-a820-cd09a30e088d.png)

2. Content -> Design -> Configuration -> Edit a Store -> Breeze ->  Enable Breeze Experience -> No
![imagen](https://user-images.githubusercontent.com/61665158/224705299-35fb50af-10ff-4160-a3f9-d6adc1c2164f.png)

Thank you.

Regards

**Comment by steveschmitt** [comment]
This is not the right repo for your issue.  I think you want something under https://github.com/breezefront
