### ISSUE TITLE
Entity custom validation fails....

### ISSUE THREAD

**Issue by MHacker9404** [Breeze/breeze-client#8]
I have implemented a custom validation function that is attached to an EntityType, let's say FooEntity.  If I have a collection of FooEntity --> FooEntity[], and call validateEntity() on a specific instance of FooEntity within the collection, the validator is run against all instances in the collection.  Not just the specific instance.

**Comment by jtraband** [comment]
I'd need to see some of the code to diagnose this better.

**Comment by MHacker9404** [comment]
Should have an example set up today

**Comment by MHacker9404** [comment]
got a sample set up at [BreezeEntityValidation](https://github.com/MHacker9404/BreezeEntityValidation).  This is based on the PluralSight breeze course.  The Customer entity has 2 validations on it - a property validation that fires for changes on everything, and an entity validation that doesn't fire on anything.  This example is much simpler than the actual code that I'm dealing with.  The entity-validation in my actual code is based on changes to entities in a collection that the parent entity needs to monitor.

**Comment by jtraband** [comment]
Ok, I'm running your test app but I'm not sure exactly what the bug is.  Can you describe the steps that I should go thru within this app to cause this specific bug?

**Comment by MHacker9404** [comment]
I’ll explain in better detail this evening – gimme a couple of hours - tanks

**Comment by jtraband** [comment]
Ok, I do see one other major issue with your validation implementation.  You are adding a new validator every time an entity is constructed.  Validators are 'type' specific, so you only need one per type not one per instance.  So in your current app, you have 3 or 4 name validators and also 3 or 4 age validators all running at the same time.  This is a perf killer even with a small app. Better would be to check if the validator already exists before add it in your constructor or even better just add all of your validators immediately after the metadataStore is first created.  A common way to do this is to call 'registerAnnotations' ( below) immediately after your metadataStore is initialized.  This will look up all custom property annotations ( which includes validations) and adds them all exactly once. 

 private registerAnnotations(metadataStore: MetadataStore) {
    metadataStore.getEntityTypes().forEach((t: EntityType) => {
      const et = <EntityType>t;
      const ctor = <any>et.getCtor();
      if (ctor && ctor.getEntityTypeAnnotation) {
        const etAnnotation = <EntityTypeAnnotation>ctor.getEntityTypeAnnotation();
        et.validators.push(...etAnnotation.validators);
        etAnnotation.propertyAnnotations.forEach((pa) => {
          const prop = et.getProperty(pa.propertyName);
          prop.validators.push(...pa.validators);
          prop.displayName = pa.displayName;
          prop.custom = pa.custom;
        });
      }
    });


Example 'getEntityTypeAnnotation' on a single type ( just add a static method with this name to any types that need validations or other breeze property annotations.

static getEntityTypeAnnotation() {
      const propAnnotations = [
        new EntityPropertyAnnotation('weeksPerYear', {
          displayName: 'Weeks',
          validators: [ rangeValidator({ minValue: 0, maxValue: 52 }) ]
        }),
        new EntityPropertyAnnotation('daysPerWeek', {
          displayName: 'Days',
          validators: [ rangeValidator({ minValue: 0, maxValue: 7 }) ]
        }),
        new EntityPropertyAnnotation('hoursPerDay', {
          displayName: 'Hours',
          validators: [ rangeValidator({ minValue: 0, maxValue: 24 }) ]
        })
      ];

    return new EntityTypeAnnotation({
      validators: [],
      propertyAnnotations: propAnnotations
    });
  }

**Comment by MHacker9404** [comment]
I gotcha – how does this tie in to the static initializer that the tools create?

**Comment by steveschmitt** [comment]
@MHacker9404 I think @marcelgood did an example of registering custom validations in the [TempHire](https://github.com/Breeze/temphire.angular/tree/master/TempHire/app/core/services) sample application.
